### ISSUE TITLE
Remove length from Stateful Iterators

### ISSUE THREAD

**Issue by wkearn** [meggart/DiskArrays.jl#142]
CI is failing on nightly because of this change: https://github.com/JuliaLang/julia/pull/51747

DiskArrays calls `length` on a `Stateful` iterator here:

https://github.com/meggart/DiskArrays.jl/blob/3689544f68f2ac10db8b6f127384df892a1a913f/src/iterator.jl#L40-L60

**Comment by rafaqz** [comment]
Surely this is a breaking change to julia Base?

**Comment by rafaqz** [comment]
@meggart we may need to define our own `DiskStateful` iterator and define `length` on it as in this case we know it is correct.

**Comment by felixcremer** [comment]
This is closed by #145 .
