### ISSUE TITLE
map is broken, includeing missing collect_similar for DiskGenerator

### ISSUE THREAD

**Issue by felixcremer** [meggart/DiskArrays.jl#144]
The `DiskGenerator` is missing an implementation of `collect_similar` which makes the filter function not work properly. See https://github.com/yeesian/ArchGDAL.jl/issues/409 for the details.

**Comment by rafaqz** [comment]
`map` is actually broken in a _lot_ of ways.

I'm keen to try my very old idea of caching a whole column of chunks for `iterate` instead of a single chunk. Then iteration can follow the normal order and all of these problems go away.

**Comment by meggart** [comment]
> I'm keen to try my very old idea of caching a whole column of chunks for iterate instead of a single chunk. Then iteration can follow the normal order and all of these problems go away. We can just delete DiskGenerator and DiskZip completely.

Won't this very easily lead to Out-Of-Memory errors for large multi-dimensional arrays where you just can not keep all chunks along the first dimension in memory? Very easy to construct examples where this fails. 

Another option might just be to completely deprecate `map`, `broadcast` and `reduce` from DiskArrays and refer to DiskArrayEngine. Alternatively we could of course try to come up with more principled implementations, but I don't know if it would be worth the effort...

**Comment by rafaqz** [comment]
Does `map` work in DiskArrayEngine ?

It just seems to me that we are silently returning the _wrong answer_ for map currently, which is worse OOM errors. I am really keen to not silently return the wrong result ever.

We could always fall back to loading partial chunks if the whole column is too large for memory.

**Comment by meggart** [comment]
Is this resolve by #198 ?

**Comment by asinghvi17** [comment]
I just tried the example from ArchGDAL, and it seems like it is correct:

```julia
issetequal(filter(!(==(-9999)), collect(o)), filter(!(==(9999)), o)) # true
```

so this should be working now.
