### ISSUE TITLE
ArchGDAL tests on julia 1.6 fail because `@kwdef` is not defined

### ISSUE THREAD

**Issue by felixcremer** [meggart/DiskArrays.jl#160]
On julia 1.6 the ArchGDAL tests fail with the following.
We would either need to restrict the julia version bound for DiskArrays to 1.9 or higher or we would change the `@kwdef` to `Base.@kwdef`.

```julia

ERROR: LoadError: LoadError: LoadError: LoadError: UndefVarError: @kwdef not defined
Stacktrace:
  [1] top-level scope
    @ :0
  [2] include(mod::Module, _path::String)
    @ Base ./Base.jl:384
  [3] include(x::String)
    @ DiskArrays ~/.julia/packages/DiskArrays/LD5Gn/src/DiskArrays.jl:1
  [4] top-level scope
    @ ~/.julia/packages/DiskArrays/LD5Gn/src/diskarray.jl:30
  [5] include(mod::Module, _path::String)
    @ Base ./Base.jl:384
  [6] include(x::String)
    @ DiskArrays ~/.julia/packages/DiskArrays/LD5Gn/src/DiskArrays.jl:1
  [7] top-level scope
    @ ~/.julia/packages/DiskArrays/LD5Gn/src/DiskArrays.jl:15
  [8] include
    @ ./Base.jl:384 [inlined]
  [9] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::String)
    @ Base ./loading.jl:1235
 [10] top-level scope
    @ none:1
 [11] eval
    @ ./boot.jl:360 [inlined]
 [12] eval(x::Expr)
    @ Base.MainInclude ./client.jl:446
 [13] top-level scope
    @ none:1
in expression starting at /home/runner/.julia/packages/DiskArrays/LD5Gn/src/batchgetindex.jl:7
in expression starting at /home/runner/.julia/packages/DiskArrays/LD5Gn/src/batchgetindex.jl:7
in expression starting at /home/runner/.julia/packages/DiskArrays/LD5Gn/src/diskarray.jl:30
in expression starting at /home/runner/.julia/packages/DiskArrays/LD5Gn/src/DiskArrays.jl:1
```

**Comment by rafaqz** [comment]
We are also using the `@assume_effects` macro so it wont work on 1.6 anyway.

I think we need to bump ArchGDAL to 1.9.

I already did this for a bunch of JuliaGeo packages, and given our available dev time supporting 1.6 is not worth the effort anymore

**Comment by felixcremer** [comment]
Yes, we should bump packages to 1.9 but the main problem is, that DiskArrays claims to be compatible to 1.6 and therefore the new version is tried in CI for ArchGDAL.

**Comment by rafaqz** [comment]
DidkArrays is lying! 😂

We need a PR fixing the DidkArrays julia version to 1.9 and also testing on 1.9.

**Comment by meggart** [comment]
Yes, but we are still a bit in trouble, since the package manager will try to install 0.4.0 for older julia versions. Whenever we make PRs to downstream packages to upgrade DiskArrays we should make sure to require at least DiskArrays 0.4.1 to avoid e.g. julia 1.8 users getting a broken package version

**Comment by rafaqz** [comment]
We need to yank 0.4.0

**Comment by meggart** [comment]
https://github.dev/meggart/General/tree/yank_diskarrays_04

**Comment by meggart** [comment]
This has been around for 3 weeks now. @rafaqz do you have any ideas how to draw the attention of a registry maintainer towards this PR https://github.com/JuliaRegistries/General/pull/102850

**Comment by rafaqz** [comment]
I'm pestering people on slack, see if they respond. 

People have been doing unnecessary yanks and Pkg isn't good at handling it, but this is a very legitimate use case.

**Comment by meggart** [comment]
I think this is resolved now.
