### ISSUE TITLE
Performance and precision of sum(ncvar_float32)

### ISSUE THREAD

**Issue by Alexander-Barth** [meggart/DiskArrays.jl#188]
Prompted by [this discussion](https://discourse.julialang.org/t/ncdatasets-performance-issues-deriving-fast-minimum-maximum-value-as-too-slow/118468/2) , I had a new look at the `mapreduce` functionality (actually just the  `sum` function)  of DiskArray. 
Here are some observations that I want to share that maybe are helpful.

Here is the example NetCDF file:

```julia
fname = "/tmp/test_sample.nc"
ds = NCDataset(fname,"c")

defDim(ds,"lon",1024)
defDim(ds,"lat",1024)
defDim(ds,"time",64)
v = defVar(ds,"temperature",Float32,("lon","lat","time"),chunksizes = (512,512,1))
for n = 1:size(v,3)
    v[:,:,n] = fill(n,1024,1024)
end
close(ds)
```
With  DiskArrays v0.4.4 and NetCDF v0.12.0, I do not get the "correct" output of `sum` when applied to the NetCDF variable `temperature`:

```julia
import NetCDF

fname = "/tmp/test_sample.nc"

nc = NetCDF.open(fname);
ncvar = nc["temperature"];

@show sum(Array(ncvar))
# output 2.181038f9
# good, correct result is (64*65)/2 * 1024^2 = 2.18103808e9

res = @time sum(ncvar)
res = @time sum(ncvar)
res = @time sum(ncvar)

@show res
# output 1.0737418f9
# different from sum(Array(ncvar))

#  8.356526 seconds (469.77 M allocations: 32.250 GiB, 13.48% gc time)
```

So the output of `sum(Array(ncvar))` is  `2.181038f9` (correct) while the output of  `sum(ncvar)` is `1.0737418f9`.
Note this issue does not occur if all elements of `ncvar` are randomly initialized and ~1. I don't think that there is a bug in DiskArrays, but the rounding problem of float 32 is hitting us badly here.

Here is a very naive implementation for the sum:

```julia
using CommonDataModel
using NCDatasets
using DiskArrays


function testsum(v)
    ci = DiskArrays.eachchunk(v)

    Tdata = eltype(v)
    Tbuffer = eltype(v.var)

    N = ndims(v)
    data = Array{Tdata,N}(undef,length.(first(ci)))
    buffer = Array{Tbuffer,N}(undef,length.(first(ci)))

    res = Tdata(0)
    for indices in ci
        NCDatasets.load!(v,data,buffer,indices...)
        res += sum(data)
    end
    return res
end

fname = "/tmp/test_sample.nc"

ds = NCDataset(fname,"r")
v = ds["temperature"]
res = @time testsum(v)
res = @time testsum(v)
res = @time testsum(v)

@show res
# output  2.181038f9
# 0.066360 seconds (4.38 k allocations: 2.235 MiB)
```

Surprisingly this native implementation is much faster (0.066360 s vs  8.356526 s; the difference persist for larger arrays) and does not suffer from the loss of precision.
But obviously it is much less flexible that the whole machinery in DiskArrays, and can fail in different ways (e.g. the last chunks is smaller).
So maybe this information is helpful for some specialized implementations (in particular where `dims = :`).

Let me know if you see a problem with this benchmark.

**Comment by rafaqz** [comment]
@Alexander-Barth this should solve it:

```julia
function Base.sum(v::AbstractDiskArray)
    sum(eachchunk(DiskArrays.eachchunk(v))) do chunk
        sum(v[chunk...])
    end
end
```

If you want to make a PR we could also define a similar method for `sum`, `mean`, `count` and maybe others that follow the same pattern, that would be amazing.

It would be really nice to get PRs fixing these problems rather than just demonstrations ;)

**Comment by Alexander-Barth** [comment]
It is indeed as fast as the specialized implementation:
```julia
function Base.sum(v::AbstractDiskArray)
    sum(DiskArrays.eachchunk(v)) do chunk # dropping one eachchunk
        sum(v[chunk...])
    end
end
```
```
julia> res = @time sum(ncvar)
  0.065856 seconds (6.65 k allocations: 256.277 MiB, 3.03% gc time)
2.181038f9
```

I should be able to get some time for a PR :-)
