### ISSUE TITLE
Implement reverse indexing

### ISSUE THREAD

**Issue by meggart** [meggart/DiskArrays.jl#6]
`zarr[end:-1:1, :, :]` not working

There is probably some lastindex implementation missing. Should be added as a new indexing method

**Comment by meggart** [comment]
Initially reported [here](https://github.com/esa-esdl/ESDL.jl/issues/174)

**Comment by felixcremer** [comment]
I had a look into it with PseudoDiskArray and lastindex works with a fallback method from Base.
You can check this with a[end]
But the issue here is, that indexing with StepRange is not yet implemented.
