### ISSUE TITLE
`view` with an AbstractRange (not AbstractUnitRange) is broken

### ISSUE THREAD

**Issue by rafaqz** [meggart/DiskArrays.jl#61]
This is because `subsetchunks` is specifically only written for `reverse`

https://github.com/meggart/DiskArrays.jl/blob/d0da1e0f4bae3f464b873f1659689c6ece398a18/src/chunks.jl#L43-L50

Should we just subset it as if there is not step? will that work?

Edit: it doesn't.

Maybe the batch PR can work for this as well? views like this are very useful for reducing the size of (very) large rasters for plotting. Rasters.jl has been using this prior to 0.3.

**Comment by meggart** [comment]
Can you test with this branch https://github.com/meggart/DiskArrays.jl/pull/62 

Should fix most cases, at least those where the subset is ordered.
