### ISSUE TITLE
Documentation is missing?

### ISSUE THREAD

**Issue by gdkrmr** [meggart/DiskArrays.jl#87]
The links of the documentation badges go to 404 errors

https://meggart.github.io/DiskArrays.jl/stable

**Comment by meggart** [comment]
Pushing to the gh-pages branch is working now. I guess/hope we will see some docs whenever we tag a new version.

**Comment by gdkrmr** [comment]
The badges still go to a 404 error.

**Comment by Sonicious** [comment]
still an issue...
